In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

In [8]:
df1 = pd.read_csv('경기도내등록장애인집계현황(읍면동별,유형별,정도별).csv', encoding = 'cp949')

In [13]:
from matplotlib import font_manager, rc
from matplotlib.ticker import FuncFormatter

In [37]:
def person(x, pos):
    return f'{np.int64(x)}'

In [46]:
df1_totar = df1.iloc[:, [7,10]]
df1_totar

      심한장애인수(합계)  심하지않은장애인수(합계)
0           84.0            0.0
1           62.0           39.0
2            9.0            0.0
3           33.0            0.0
4           32.0           11.0
...          ...            ...
6476         2.0            1.0
6477         3.0            0.0
6478         1.0            9.0
6479         1.0            0.0
6480        22.0            0.0

[6481 rows x 2 columns]

In [48]:
df1

,시군명,구명,읍면동명,장애유형,등록장애인수(합계),등록장애인수(남성),등록장애인수(여성),심한장애인수(합계),심한장애인수(남성),심한장애인수(여성),심하지않은장애인수(합계),심하지않은장애인수(남성),심하지않은장애인수(여성)
0,가평군,NaN,가평읍,지적,84.0,51.0,33.0,84.0,51.0,33.0,0.0,0.0,0.0
1,가평군,NaN,가평읍,뇌병변,101.0,58.0,43.0,62.0,32.0,30.0,39.0,26.0,13.0
2,가평군,NaN,가평읍,자폐성,9.0,9.0,0.0,9.0,9.0,0.0,0.0,0.0,0.0
3,가평군,NaN,가평읍,정신,33.0,15.0,18.0,33.0,15.0,18.0,0.0,0.0,0.0
4,가평군,NaN,가평읍,신장,43.0,22.0,21.0,32.0,15.0,17.0,11.0,7.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6476,하남시,NaN,풍산동,심장,3.0,2.0,1.0,2.0,2.0,0.0,1.0,0.0,1.0
6477,하남시,NaN,풍산동,호흡기,3.0,2.0,1.0,3.0,2.0,1.0,0.0,0.0,0.0
6478,하남시,NaN,풍산동,간,10.0,6.0,4.0,1.0,0.0,1.0,9.0,6.0,3.0
6479,하남시,NaN,풍산동,안면,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
6480,하남시,NaN,풍산동,자폐성,22.0,20.0,2.0,22.0,20.0,2.0,0.0,0.0,0.0

In [53]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6481 entries, 0 to 6480
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   시군명            6481 non-null   object
 1   구명             2949 non-null   object
 2   읍면동명           6481 non-null   object
 3   장애유형           6481 non-null   object
 4   등록장애인수(합계)     6480 non-null   float64
 5   등록장애인수(남성)     6474 non-null   float64
 6   등록장애인수(여성)     6440 non-null   float64
 7   심한장애인수(합계)     6437 non-null   float64
 8   심한장애인수(남성)     6398 non-null   float64
 9   심한장애인수(여성)     6398 non-null   float64
 10  심하지않은장애인수(합계)  6434 non-null   float64
 11  심하지않은장애인수(남성)  6399 non-null   float64
 12  심하지않은장애인수(여성)  6398 non-null   float64
dtypes: float64(9), object(4)
memory usage: 658.4+ KB