In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import os
import plotly
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import seaborn as sns
import matplotlib.pyplot as plt
import json
%matplotlib inline

In [2]:
os.listdir()

['.ipynb_checkpoints',
 '.음식점, 관광지, 쇼핑점 수로 지역 테마 파악하기.ipynb',
 'Data_1.ipynb',
 'data_2.ipynb',
 'KC_618_LLR_RSTRT_CNBAS_TRND_2021.csv',
 'KC_619_DMSTC_TRV_CNSMP_STATN_BIZAEA_MAP_2021.csv',
 '경기도내등록장애인집계현황(읍면동별,유형별,정도별).csv',
 '사망원인.csv',
 '인총 주택 정보 데이터.csv',
 '지역 테마 파악하기.ipynb']

In [18]:
df=pd.read_csv('KC_618_LLR_RSTRT_CNBAS_TRND_2019.csv')

In [19]:
dff=pd.read_csv('KC_619_DMSTC_TRV_CNSMP_STATN_BIZAEA_MAP_2019.csv')

In [20]:
df.head()

,sido_nm,sgg_nm,hadm_cd,ksic_cd,cate_nm,mcate_cd,facility_cnt,residnt_cnt_sum,FILE_NAME,base_ymd
0,강원도,강릉시,42150,56111,한식,벌집삼겹살,2,162905,KC_618_LLR_RSTRT_CNBAS_TRND_2019,20200214
1,강원도,강릉시,42150,56111,한식,몸보신,38,162905,KC_618_LLR_RSTRT_CNBAS_TRND_2019,20200214
2,강원도,강릉시,42150,56111,한식,한정식,19,162905,KC_618_LLR_RSTRT_CNBAS_TRND_2019,20200214
3,강원도,강릉시,42150,56111,한식,생고기/등심,98,162905,KC_618_LLR_RSTRT_CNBAS_TRND_2019,20200214
4,강원도,강릉시,42150,56111,한식,국수전문,176,162905,KC_618_LLR_RSTRT_CNBAS_TRND_2019,20200214

In [37]:
dff.head()

,sido_nm,sgg_nm,hadm_cd,atrctn_cnt,rstrt_cnt,shopng_cnt,residnt_cnt_sum,FILE_NAME,base_ymd
0,강원도,강릉시,42150,308,4685,460,162905,KC_619_DMSTC_TRV_CNSMP_STATN_BIZAEA_MAP_2019,20200214
1,강원도,고성군,42820,105,795,117,18628,KC_619_DMSTC_TRV_CNSMP_STATN_BIZAEA_MAP_2019,20200214
2,강원도,동해시,42170,85,1929,247,68772,KC_619_DMSTC_TRV_CNSMP_STATN_BIZAEA_MAP_2019,20200214
3,강원도,삼척시,42230,135,1597,209,45409,KC_619_DMSTC_TRV_CNSMP_STATN_BIZAEA_MAP_2019,20200214
4,강원도,속초시,42210,79,2594,210,63203,KC_619_DMSTC_TRV_CNSMP_STATN_BIZAEA_MAP_2019,20200214

In [38]:
sido_rsd=df[['sido_nm', 'sgg_nm', 'residnt_cnt_sum']].drop_duplicates().reset_index().drop(columns=['index'])
sido_rsd=sido_rsd.groupby(by=['sido_nm'], as_index=False).sum()

In [39]:
fig=px.pie(sido_rsd, values='residnt_cnt_sum', names='sido_nm')
fig.update_layout(title_text='시도별 인구 비율', title_x=0.47, font=dict(family="Noto Sans KR",size=14))
fig.show()

In [40]:
sido=dff[['sido_nm', 'atrctn_cnt', 'shopng_cnt']].groupby(by='sido_nm').sum().reset_index()

In [41]:
fig=px.pie(sido, values='atrctn_cnt', names='sido_nm')
fig.update_layout(title_text='시도별 관광지 비율', title_x=0.47, font=dict(family="Noto Sans KR",size=14))
fig.show()

In [42]:
fig=px.pie(sido, values='shopng_cnt', names='sido_nm')
fig.update_layout(title_text='시도별 쇼핑점 비율', title_x=0.47, font=dict(family="Noto Sans KR",size=14))
fig.show()

In [68]:
def city_pop(city):
    df_2_city=df_2[df_2['sido_nm']==city]
    df1=df_2_city[['sgg_nm', 'residnt_cnt_sum']].drop_duplicates().reset_index().drop(columns=['index'])
    df1=pd.merge(df1, df_2_city[['sgg_nm', 'facility_cnt']].groupby(by=['sgg_nm']).sum().reset_index(), on='sgg_nm', how='right')
    df1[['fac_rsd']]=df1.apply(lambda x: (x['facility_cnt']/x['residnt_cnt_sum'])*100, axis=1)
    fig=px.pie(df1, values='residnt_cnt_sum', names='sgg_nm')
    fig.update_layout(title_text=city+' 인구 비율', title_x=0.3, font=dict(family="Noto Sans KR",size=14))
    fig.show()
    return df_2_city, df1

def city_pop2(city):
    df_2_city=df_2[df_2['sido_nm']==city]
    df1=df_2_city[['sgg_nm', 'residnt_cnt_sum']].drop_duplicates().reset_index().drop(columns=['index'])
    df1=pd.merge(df1, df_2_city[['sgg_nm', 'facility_cnt']].groupby(by=['sgg_nm']).sum().reset_index(), on='sgg_nm', how='right')
    df1[['fac_rsd']]=df1.apply(lambda x: (x['facility_cnt']/x['residnt_cnt_sum'])*100, axis=1)
    fig=px.pie(df1, values='residnt_cnt_sum', names='sgg_nm')
    fig.update_traces(textposition='inside', textfont_size=20)
    fig.update_layout(title_text=city+' 인구 비율', title_x=0.3, font=dict(family="Noto Sans KR",size=14))
    fig.show()
    return fig

def city_pop3(city):
    df_2_city=df_2[df_2['sido_nm']==city]
    df1=df_2_city[['sgg_nm', 'residnt_cnt_sum']].drop_duplicates().reset_index().drop(columns=['index'])
    df1=pd.merge(df1, df_2_city[['sgg_nm', 'facility_cnt']].groupby(by=['sgg_nm']).sum().reset_index(), on='sgg_nm', how='right')
    df1[['fac_rsd']]=df1.apply(lambda x: (x['facility_cnt']/x['residnt_cnt_sum'])*100, axis=1)
    fig=px.pie(df1, values='residnt_cnt_sum', names='sgg_nm')
    fig.update_traces(textposition='inside', textinfo='percent+label', textfont_size=20)
    fig.update_layout(title_text=city+'인구 비율', title_x=0.3, font=dict(family="Noto Sans KR",size=14), showlegend=False)
    fig.show()
    return fig

In [71]:
df_2_seoul, df1=city_pop('서울특별시')

ValueError: Columns must be same length as key

In [63]:
dff_seoul=dff[dff['sido_nm']=='서울특별시'].groupby(by='sgg_nm').sum().reset_index()
dff_seoul[['atrctn_rsd']]=dff_seoul.apply(lambda x: (x['atrctn_cnt']/x['residnt_cnt_sum'])*100, axis=1)
dff_seoul[['shopng_rsd']]=dff_seoul.apply(lambda x: (x['shopng_cnt']/x['residnt_cnt_sum'])*100, axis=1)

ValueError: Columns must be same length as key

In [64]:
def bar_scatter(df, x, y1, y2, t, city):

    fig=go.Figure()

    pop=go.Scatter(
        x=df[x], y=df[y1],
        mode='lines+markers',
        xaxis = 'x',
        yaxis='y1',
        line_color='rgb(128, 0, 128)',
        name='인구 수 대비 '+t
    )
    fac=go.Bar(
        x=df[x], y=df[y2],
        xaxis = 'x',
        yaxis='y2',
        marker=dict(
            color='rgba(50, 171, 96, 0.6)',
            line=dict(
                color='rgba(50, 171, 96, 1.0)',
                width=1),
        ),
        name=t
    )

    data=[pop, fac]

    layout=dict(

        geo=dict(
            showframe=True,
            showcoastlines=True
        ),

        yaxis=dict(
            side='right',
            overlaying='y2',
            anchor='x',
            rangemode='tozero'
        ),

        yaxis2=dict(
            side='left',
            anchor='x',
            rangemode='tozero'
        ),

        plot_bgcolor='rgb(248, 248, 255)',
        legend=dict(x=0, y=1.15, font_size=11)
    )

    fig=go.Figure(data=data, layout=layout)
    fig.update_layout(title_text=city, title_x=0.5, font=dict(family="Noto Sans KR",size=14))
    return fig

In [66]:
chart=bar_scatter(df1, 'sgg_nm', 'fac_rsd', 'facility_cnt', '음식점수', '서울특별시')
chart

NameError: name 'df1' is not defined

In [67]:
df_2=pd.read_csv('KC_618_LLR_RSTRT_CNBAS_TRND_2019_2.csv')